### ISSUE TITLE
Provide option to push Support Kit VC on nav controller

### ISSUE THREAD

**Issue by stevemoser** [radialpoint/SupportKit#2]
The requirements I have been given includes push a zendesk 'help' vc onto a navigation view controller stack and the modal looking animation default animation doesn't work well for that. Might there be an option for that or a way I can configure support kit to do that?

**Comment by mspensieri** [comment]
It's been a long time coming, but this is now possible with v2.8.0. Check out the `newConverstionViewController` method, which creates and returns a view controller that you can present in any way you choose.
