### ISSUE TITLE
Ability to send images and other files in the conversation

### ISSUE THREAD

**Issue by felix100000** [radialpoint/SupportKit#28]
I think this is pretty important. A user should be able to send the supporter images and other files that might help resolving issues with the app. Same thing, a supporter should be able to send files in the conversation by replying with an email with attachments.

**Comment by mspensieri** [comment]
Image upload is now supported as of v2.9.0, both through the UI and through the `sendImage:withProgress:completion` API of [SKTConversation](http://docs.supportkit.io/api/Classes/SKTConversation.html)

Generic file upload is not yet supported. Feel free to open a new issue if this is still desired

**Comment by williamsjj** [comment]
The docs for ```sendImage:withProgress:completion``` don't specify if it expects a UIImage or UIData: http://docs.supportkit.io/api/Classes/SKTConversation.html#//api/name/sendImage:withProgress:completion:

**Comment by mspensieri** [comment]
@williamsjj Wow great point, could be a bug in the doc generation tool we use. The actual method signature in code is the following:

`-(void)sendImage:(UIImage *)image withProgress:(SKTImageUploadProgressBlock)progressBlock completion:(SKTImageUploadCompletionBlock)completionBlock;`

**Comment by williamsjj** [comment]
Thanks Mike!
