### ISSUE TITLE
Chat leaks Zendesk auto response when opening ticket.

### ISSUE THREAD

**Issue by williamsjj** [radialpoint/SupportKit#36]
After updating to SupportKit 2.5.1, the chat function has started leaking part of the auto-response from Zendesk:

![photo](https://cloud.githubusercontent.com/assets/119410/5311357/a61caf16-7c01-11e4-8ddf-45d74e80cdec.png)

**Comment by mspensieri** [comment]
This should no longer be an issue with the official Zendesk integration. Also, auto-replies are now supported natively in SupportKit
