### ISSUE TITLE
Appending to ticket

### ISSUE THREAD

**Issue by Dids** [radialpoint/SupportKit#38]
I'm not sure if this is a bug, or expected behavior, but I just noticed something odd.

A user sent me three sentences, all as separate messages, but sent at roughly the same time.
Zendesk created 3 tickets, even though the sender is the same for each one of them.

Is this just because Zendesk didn't create the first ticket "in time" to append to it, or is this SupportKit related?

**Comment by mspensieri** [comment]
This should be fixed now! Thanks for the reporting this
