### ISSUE TITLE
Support "content-available" property in push notification payload

### ISSUE THREAD

**Issue by shuyuanshi** [radialpoint/SupportKit#39]
Can you add "content-available":1 in the push notification JSON? so that even the app is in background, we can update the app icon badge value when there is push notification from SupportKit

Thanks

**Comment by ahamedsaifudeen** [comment]
This is very much needed. Since content-available=1 is not sent in the push JSON, the notification appears only if the app is up and running. Please add this at the earliest.

**Comment by mspensieri** [comment]
Content-Available flag should now be included in the push payload. Thanks for reporting this!

**Comment by ShafiqEssani** [comment]
I've added content-available, when app is running in background the code block is not working.
Everything works fine on IOS.
What the heck is wrong with this Android. :(

**Comment by ShafiqEssani** [comment]
![image](https://user-images.githubusercontent.com/24293253/38677685-6978dc5a-3e78-11e8-96e4-2a3314bb2501.png)

**Comment by mspensieri** [comment]
Sorry @ShafiqEssani, I'm not quite sure I understand the problem? This is an old feature request from nearly 3 years ago.

> when app is running in background the code block is not working.

which code block are you referring to?

> Everything works fine on IOS.
> What the heck is wrong with this Android. :(

Are you talking about [smooch-android](https://github.com/smooch/smooch-android)?

> I've added content-available

Smooch sends push notifications itself, it doesn't handle push notifications sent by other sources (like postman). Also I believe the `content-available` flag is an iOS-specific parameter. It shouldn't really be doing anything on Android. What behaviour are you expecting?

**Comment by ShafiqEssani** [comment]
Okay let me explain you the whole scenario:

I’m working with push notifications in one of my Ionic 2 Application using FCM.

Just stucked when the app is not running in the foreground that means when the app is closed and push notification triggers, its showing up properly but when its tapped the application starts up but the code after push is not working :s

pushObject.on(‘notification’).subscribe((data: any) => {

console.log(‘Data returned’, data);
//if user using app and push notification comes
if (data.additionalData.foreground) {
console.log(“app is running”);
} **else {
//if user NOT using app and push notification comes
//TODO: Your logic on click of push notification directly
console.log(‘Push notification clicked’, data);
}**
});

Forget about the above screenshot for the moment.
I'm sending notification from firebase console. PUSH is coming in notification panel. BUT when clicked the code block that is bold is not running.
I’m unable to see this ‘Push notification clicked’ log, how to check my after push code is working properly?

This thing is running fine in iOS. but on Android this is cancer now.

Any help will be highly appreciated!
Thanks.

**Comment by mspensieri** [comment]
Thanks for the details. I'm still not sure how this relates to Smooch, or this repository, however. Unfortunately I'm not familiar with Ionic or FCM, so I'm afraid I won't be much help to you 😞

**Comment by bguidolim** [comment]
Hey! Sorry for commenting in a closed issues, but it seems that `content-available` flag is not coming with the notifications anymore.
Is that correct?
