### ISSUE TITLE
Programmatically send message

### ISSUE THREAD

**Issue by sprynmr** [radialpoint/SupportKit#41]
We allow users to report issues via this tool, and then have a conversation around them. They select the object they are having an issue with in our system (a guest card), and then start the conversation. Right now we set a custom user property each time, but that doesn't really fit the bill since there's no history on that property. Anyway to send a custom message so we could say "Reporting issue with guest card: Bob Spryn"?

**Comment by sprynmr** [comment]
Damn. Found it in the conversation class. Totally missed it the first time around.

**Comment by gozman** [comment]
No worries. We'll improve our documentation of this feature. It's hot off the presses!

**Comment by sprynmr** [comment]
It's all badass!
