### ISSUE TITLE
Bundle not loading when used with another Swift pod

### ISSUE THREAD

**Issue by zeusent** [radialpoint/SupportKit#42]
Ok, so I have this app where I use on pod that's written in Swift. Doing so makes me add the `use_frameworks!` flag in my **Podfile**.

The app compiles and all but it then complains that the `SupportKit.bundle` is not present in the app binary.

I tried adding it manually (even though that defeats the purpose of using CocoaPods) and it seems to be fine. Until I tried submitting the app to the store. I then got this error:

![screen_shot_2015-04-14_at_17 34 44-1](https://cloud.githubusercontent.com/assets/777591/7587462/17446910-f8bf-11e4-90c4-3e6e7dbb9db3.png)

Could anyone help me with this please?

P.S: My Podfile looks like this:

    pod 'SupportKit'
    pod 'NKJSON'
    use_frameworks!

**Comment by mspensieri** [comment]
@zeusent I think I have a fix, so I'd like to provide you with a test build to see if it indeed works for you. Could you please email me mikespensieri@supportkit.io and I'll give you the information

**Comment by mspensieri** [comment]
This should be fixed with v2.8.0. I'll close this issue for now, but if it still reproduces, feel free to reopen!
