### ISSUE TITLE
Way to delete or clear conversation.

### ISSUE THREAD

**Issue by psy2k** [radialpoint/SupportKit#47]
Is there a way to delete a conversation or clear it entirely? For example if a user logs out and a new one logs in I don't want the second one to see the support messages from the first one. 

I've found the messages property in SKTConversation but it is readonly.

**Comment by pmilanez** [comment]
:+1: for that!

**Comment by ejeklint** [comment]
:+1: yes!

**Comment by mspensieri** [comment]
v2.10.0 now supports identifying your users through a `userId` property. You can now properly manage user sessions on a single device, and across devices.

http://docs.supportkit.io/ios/#users-on-multiple-devices
