### ISSUE TITLE
Keyobard Dismiss!

### ISSUE THREAD

**Issue by EMidee66** [radialpoint/SupportKit#48]
Hello,

Is there a way to dismiss the keyboard with the return key? I don't want to use the back button on the navigation bar as it uses too much space.

Thank You!

**Comment by mspensieri** [comment]
@EMidee66 could you please clarify your request? What do you mean when you say the back button takes too much space?

The return key currently causes a carriage return in the text input, so the user can send multi-line messages. The keyboard can be dismissed by swiping down from the middle of the screen, or, if the conversation is not within a navigation controller, you can simply tap the navigation bar.

**Comment by EMidee66** [comment]
Oh the back button on the navigation bar. I tried to access the keyboard so I could change the Return Key to close the keyboard but I couldn't. I didn't like the navigation bar since it took too much space.
Hey Mike thank you very much for your support. By the way Donnie Darko it's a great movie. :)
