### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by nickoneill** [radialpoint/SupportKit#52]
Working on an iOS 9 app with watchOS component and bitcode support is required. Here's the current error message when I attempt to enable bitcode for my app:

`..Pods/SupportKit/SupportKit.framework/SupportKit(SKTLegacyAjaxEndpoint.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by mspensieri** [comment]
Thanks @nickoneill. We have bitcode support ready to launch, but we're waiting for Xcode7 to be publicly available before releasing it, since the new build will no longer be able to compile with Xcode6

**Comment by johankool** [comment]
Any chance of making it available on a separate branch until then?

**Comment by nickoneill** [comment]
Thanks @mspensieri! I'm with @johankool too, I'd love to get this working sooner rather than later.

**Comment by mspensieri** [comment]
You got it, v2.10.1 is out early :)

**Comment by p2** [comment]
I get this error again with Xcode 7.0.1, using SupportKit `2.10.1` installed as Pod. Reinstalling the Pod didn't help. Anybody else?

**Comment by SamBellerose** [comment]
@p2 I have the same error as you, I can't archive my project under Xcode 7.0.1

**Comment by mspensieri** [comment]
@p2 @SamBellerose would love to get some more details, can one of you open a separate issue please?

Were you able to compile with 7.0.0? Does this happen on every build, or just on archive?

**Comment by p2** [comment]
Sure. Issue #58.
