### ISSUE TITLE
Bump major version due to Xcode 7 requirement / ModelIO linker error

### ISSUE THREAD

**Issue by fatuhoku** [radialpoint/SupportKit#56]
(This comment is copied from my notes in #54)

I would really appreciate it if the SupportKit SDK versioning bump up the major number rather than a patch version.

This is because SemVer mandates that you should bump the major version number for anything that will break backwards compatibility. If I had seen that SK upgraded from 2.x to 3.x I would have saved a lot of time trying to figure out what caused ModelIO to appear even though it was not mentioned anywhere in my project!

**Comment by fatuhoku** [comment]
The update message "There is a new SupportKit version available. You have 2.9.0, version v2.10.2 is available. Visit https://github.com/radialpoint/SupportKit to download it or do a 'pod update'" ... should really warn users about this change as well.

**Comment by mspensieri** [comment]
@fatuhoku Thanks for the report, and I totally understand your frustration at this change. However, I think we have a difference of opinion here. The Semantic Versioning [spec](http://semver.org/) states the following (emphasis mine):

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced **to the public API**. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

And from the FAQ: 
> *Q: What should I do if I update my own dependencies without changing the public API?*
> A: That would be considered compatible since **it does not affect the public API**.

Semantic Versioning is really all about the public API of a framework, not about the tools required to use it. We haven't actually broken any API backwards compatibility, we just require you to use the latest version of Xcode to compile, so a bump in major version in this case should't be necessary.

Really sorry about the time you had to spend debugging this!

**Comment by fatuhoku** [comment]
@mspensieri  Thanks for your reply.  I see where you're coming from.  The public API hasn't changed. Sure.

But we're working with a compiled language, where the library's choice of "dependencies" can totally break the build.  iOS 9 doesn't count as a dependency by the way (though I totally agree that technically it is!): it's not a Cocoapod, isn't SemVered under the same scheme, and doesn't just get resolved and downloaded through `pod install`.

The bottom line is, in the world of iOS, if I upgrade from 2.9.x to 2.10.x, then ceteris paribas **I expect it to compile and run**.  If it doesn't do that, then there's no point talking about public API's not having changed — the code won't compile!  That has to be the definition of backwards incompatibility.

Hope you can see what I'm saying. Thankfully these changes in platform happen once a year :P

On a side note, why is `ModelIO` even required? I thought it's for loading 3D model files!

**Comment by mspensieri** [comment]
We don't actually use `ModelIO`, but maybe it's indirectly required by our dependency on `OpenGLES.framework` ?

**Comment by williamsjj** [comment]
Since Xcode is so tightly coupled with the iOS SDKs, I would agree that changing your minimum Xcode requirements would suggest bumping the major version.
