### ISSUE TITLE
Fails to build with Xcode 7.0.1 ("built without full bitcode")

### ISSUE THREAD

**Issue by p2** [radialpoint/SupportKit#58]
SupportKit `2.10.2` compiled fine under Xcode 7.0.0 but fails under 7.0.1. Message is:

> ld: bit code bundle could not be generated because '[...]/SupportKit/SupportKit.framework/SupportKit(SKTLegacyAjaxEndpoint.o)' was built without full bitcode.

Can't check right now whether it's only during Archive or at every build (downgraded to Xcode 7.0.0 because of this). I'm using Cocoapods.

**Comment by mspensieri** [comment]
I was able to repro, but only during archive. Thanks for the report, will update this issue with progress

**Comment by mspensieri** [comment]
I've created a new build in the xcode_7.0.1 branch that fixes this issue for me. @p2 can you confirm when you get the chance?

**Comment by p2** [comment]
Thanks; I'll update to 7.0.1 in a week or two.

**Comment by p2** [comment]
I have tested on a different machine with Xcode 7.0.1 and, adding the beta framework manually as the CocoaPods override does not work (lacking `.podspec` at the top level), it builds and links fine. Ultimately fails at code signing, so I can't 100% confirm but it seems to be good. Thanks!

**Comment by mspensieri** [comment]
Should be fixed in v2.10.3
